# Generated by Django 5.0
import uuid
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FraudRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('rule_type', models.CharField(choices=[('AMOUNT_THRESHOLD', 'Amount Threshold'), ('HIGH_RISK_COUNTRY', 'High Risk Country'), ('VELOCITY', 'Transaction Velocity'), ('USER_RISK_LEVEL', 'User Risk Level'), ('MERCHANT_CATEGORY', 'Merchant Category')], max_length=64)),
                ('parameters', models.JSONField(default=dict, help_text='Rule evaluation parameters in JSON format')),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=32)),
                ('enabled', models.BooleanField(default=True, help_text='Active status for rule evaluation')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fraud Rule',
                'verbose_name_plural': 'Fraud Rules',
                'db_table': 'fraud_rules',
            },
        ),
        migrations.AddIndex(
            model_name='fraudrule',
            index=models.Index(condition=models.Q(('enabled', True)), fields=['enabled'], name='idx_fraud_rules_enabled'),
        ),
    ]
