# Generated by Django 5.0
import uuid
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor', models.CharField(help_text='User, system service, or agent identity', max_length=255)),
                ('action', models.CharField(help_text='Action performed, e.g., RULE_UPDATE, ALERT_APPROVE', max_length=64)),
                ('entity_type', models.CharField(help_text='Type of entity affected, e.g., FraudRule, Alert', max_length=64)),
                ('entity_id', models.CharField(help_text='Identifier of the affected entity', max_length=255)),
                ('before', models.JSONField(blank=True, help_text='State prior to mutation', null=True)),
                ('after', models.JSONField(blank=True, help_text='State following mutation', null=True)),
                ('correlation_id', models.UUIDField(blank=True, help_text='Distributed trace correlation ID', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['entity_type', 'entity_id'], name='idx_audit_logs_entity'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['created_at'], name='idx_audit_logs_created_at'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['correlation_id'], name='idx_audit_logs_correlation_id'),
        ),
    ]
